### ISSUE TITLE
RoundCube 1.4.0: partially broken navigation.

### ISSUE THREAD

**Issue by vel21ripn** [johndoh/roundcube-sauserprefs#56] opened 2019-12-24 20:44 UTC
Tested on a branch: release-1.17 and release-1.18

After selecting  Settings -> Junk -> "any settings" can`t return to Mail, Contacts or other Settings without reloading page.
The problem does not depend on the skin (classic,larry,elastic).

**Comment by johndoh** [comment] 2019-12-27 12:57
Are there any errors on your browser's JS console?

**Comment by vel21ripn** [comment] 2020-01-09 11:08
Sorry for the long response.
No error in JS console.
When you try to go to any menu other than "sauserprefs", the browser does not make any requests.
The function "rcmail.command()" does not work.

**Comment by johndoh** [comment] 2020-01-09 19:43
I cannot recreate it and without an error message or something else to go on I don;t know what to tell you. Try with all other plugins may be. I'm going to close this issue only because I cannot recreate it but if you can provide an error message or some reliable steps to reproduce then please reopen.

**Closed by johndoh** 2020-01-09 19:43 UTC

**Comment by vel21ripn** [comment] 2020-01-10 12:49
I found the source of this problem! The file "sauserprefs.min.js" was from a different version.
